# Site settings
title: SNOWiQ User Manual
author: 
name: EastBanc Technologies
description: "SNOWiQ app user manual on GH-Pages contact@eastbanctech.com"
email: contact@eastbanctech.com
webpage: https://eastbanctech.com/

plugins:
  - jekyll-remote-theme
  - "jekyll-seo-tag"

# Build settings
remote_theme: pmarsceill/just-the-docs

color_scheme: foo

# Aux links for the upper right navigation
aux_links:
  "Powered by TERRAiQ":
    - "https://eastbanctech.com/products/terraiq/"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

search_enabled: true
search:
  previews: 0
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: false

#logo: "https://danhealey.github.io/ebtsnowiq/image/favicon/favicon-32x32.png"
